---
title: "Distance"
author: "Beatriz Calvo"
date: "2025-05-14"
output: html_document
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries, message=FALSE, echo=FALSE}
# rm(list = ls())

root.dir <- rprojroot::find_rstudio_root_file()

# libraries
library(tidyverse)
library(brms)
library(tidybayes)
library(bayesplot)
library(loo)
library(ggdist)
library(flextable)
library(scales) 
library(dplyr, warn.conflicts = FALSE)
library(RColorBrewer)
library(cmdstanr)
set_cmdstan_path(path = "C:/Users/bcalvo/.cmdstan/cmdstan-2.36.0")

```

```{r Load data,  message=FALSE}

## Load data

d <- readRDS(file = paste0(root.dir, "/Data/clean_data.rds"))

```

```{r Exploratory plots}

palette_sex <- c("#0D0887FF","#F89441FF" )

ggplot(data = d, aes(x = line_f, y = distance_cat, fill = sex_f, color=sex_f)) +
  theme_bw()+
  geom_boxplot(outliers=F, alpha=0.5) +
  geom_point(position=position_jitterdodge())+
  scale_fill_viridis_d("Sex", option = "plasma", end = 0.8, labels = c("Male", "Female")) +
  scale_colour_manual("Sex", values=palette_sex, labels = c("Male", "Female"))  + 
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank()) +
  theme(legend.position = "bottom", 
        legend.background =element_blank(), 
        legend.key.size = unit(0.5,"line"), 
        legend.title=element_text(size=12),
        legend.text=element_text(size=10)) +
  labs(x = "\n Line", y ="Distance moved in the cat zone (cm) \n")

ggsave(paste0(root.dir, "/Results/Graphs/EDA/distance_cat.png"), width = 5, height = 4)

# Remove data
rm(palette_sex)

```

```{r Round effect}

## Check round effect by line (Control and WT) and sex

## Data
d_round_control <- d[d$line_f %in% c("Control"),]
d_round_control$line_f <- factor(d_round_control$line_f)
d_round_control_m <- d_round_control[d_round_control$sex == "Male",]
d_round_control_f <- d_round_control[d_round_control$sex == "Female",]

d_round_w <- d[d$line_f %in% c("WT"),]
d_round_w$line_f <- factor(d_round_w$line_f)
d_round_w_m <- d_round_w[d_round_w$sex == "Male",]
d_round_w_f <- d_round_w[d_round_w$sex == "Female",]

## Models

## Control Males

# Null model
m_null <- brm(
  bf(distance_cat ~ 1),
  data = d_round_control_m,
  family = student,
  chains = 4, iter = 2000, warmup = 1000,
  cores = 4, seed = 1234,
  save_pars = save_pars(all = TRUE),
  backend = "cmdstanr",
  file = paste0(root.dir, "/Results/Round/distance_cat_round_control_m0")
)
#plot(m_null)
summary(m_null)

# Round model
m_round <- brm(
  bf(distance_cat ~ -1 + round_f),  
  data = d_round_control_m,
  family = student,
  chains = 4, iter = 2000, warmup = 1000,
  cores = 4, seed = 1234,
  save_pars = save_pars(all = TRUE),
  backend = "cmdstanr",
  file = paste0(root.dir, "/Results/Round/distance_cat_round_control_m1")
)
#plot(m_round)
summary(m_round)

# Reload models
m_null <- readRDS(paste0(root.dir, "/Results/Round/distance_cat_round_control_m0.rds"))
m_round <- readRDS(paste0(root.dir, "/Results/Round/distance_cat_round_control_m1.rds"))

# Compare models
m_null <- add_criterion(m_null, "loo")#, moment_match = TRUE) 
m_round <- add_criterion(m_round, "loo", moment_match = TRUE) 
loo_compare(m_null, m_round) %>% print(simplify = F)

## Control Females

# Null model
m_null <- brm(
  bf(distance_cat ~ 1),
  data = d_round_control_f,
  family = student,
  chains = 4, iter = 2000, warmup = 1000,
  cores = 4, seed = 1234,
  save_pars = save_pars(all = TRUE),
  backend = "cmdstanr",
  file = paste0(root.dir, "/Results/Round/distance_cat_round_control_f0")
)
#plot(m_null)
summary(m_null)

# Round model
m_round <- brm(
  bf(distance_cat ~ -1 + round_f),  
  data = d_round_control_f,
  family = student,
  chains = 4, iter = 2000, warmup = 1000,
  cores = 4, seed = 1234,
  save_pars = save_pars(all = TRUE),
  backend = "cmdstanr",
  file = paste0(root.dir, "/Results/Round/distance_cat_round_control_f1")
)
#plot(m_round)
summary(m_round)

# Reload models
m_null <- readRDS(paste0(root.dir, "/Results/Round/distance_cat_round_control_f0.rds"))
m_round <- readRDS(paste0(root.dir, "/Results/Round/distance_cat_round_control_f1.rds"))

# Compare models
m_null <- add_criterion(m_null, "loo", moment_match = TRUE) 
m_round <- add_criterion(m_round, "loo")#, moment_match = TRUE) 
loo_compare(m_null, m_round) %>% print(simplify = F)

## WT Males

# Null model
m_null <- brm(
  bf(distance_cat ~ 1),
  data = d_round_w_m,
  family = student,
  chains = 4, iter = 2000, warmup = 1000,
  cores = 4, seed = 1234,
  save_pars = save_pars(all = TRUE),
  backend = "cmdstanr",
  file = paste0(root.dir, "/Results/Round/distance_cat_round_w_m0")
)
#plot(m_null)
summary(m_null)

# Round model
m_round <- brm(
  bf(distance_cat ~ -1 + round_f),  
  data = d_round_w_m,
  family = student,
  chains = 4, iter = 2000, warmup = 1000,
  cores = 4, seed = 1234,
  save_pars = save_pars(all = TRUE),
  backend = "cmdstanr",
  file = paste0(root.dir, "/Results/Round/distance_cat_round_w_m1")
)
#plot(m_round)
summary(m_round)

# Reload models
m_null <- readRDS(paste0(root.dir, "/Results/Round/distance_cat_round_w_m0.rds"))
m_round <- readRDS(paste0(root.dir, "/Results/Round/distance_cat_round_w_m1.rds"))

# Compare models
m_null <- add_criterion(m_null, "loo")#, moment_match = TRUE) 
m_round <- add_criterion(m_round, "loo")#, moment_match = TRUE) 
loo_compare(m_null, m_round) %>% print(simplify = F)

## WT Females

# Null model
m_null <- brm(
  bf(distance_cat ~ 1),
  data = d_round_w_f,
  family = student,
  chains = 4, iter = 2000, warmup = 1000,
  cores = 4, seed = 1234,
  save_pars = save_pars(all = TRUE),
  backend = "cmdstanr",
  file = paste0(root.dir, "/Results/Round/distance_cat_round_w_f0")
)
#plot(m_null)
summary(m_null)

# Round model
m_round <- brm(
  bf(distance_cat ~ -1 + round_f),  
  data = d_round_w_f,
  family = student,
  chains = 4, iter = 2000, warmup = 1000,
  cores = 4, seed = 1234,
  save_pars = save_pars(all = TRUE),
  backend = "cmdstanr",
  file = paste0(root.dir, "/Results/Round/distance_cat_round_w_f1")
)
#plot(m_round)
summary(m_round)

# Reload models
m_null <- readRDS(paste0(root.dir, "/Results/Round/distance_cat_round_w_f0.rds"))
m_round <- readRDS(paste0(root.dir, "/Results/Round/distance_cat_round_w_f1.rds"))

# Compare models
m_null <- add_criterion(m_null, "loo")#, moment_match = TRUE) 
m_round <- add_criterion(m_round, "loo")#, moment_match = TRUE) 
loo_compare(m_null, m_round) %>% print(simplify = F)

## Remove data

rm(d_round_control, d_round_control_f, d_round_control_m, d_round_w, d_round_w_m, d_round_w_f)
rm(m_null, m_round)
```

```{r EXC-INC models}

## Models and model comparison: there are no outliers

# Null model 
m_null <- brm(
  bf(distance_cat ~ 1),
  data = d,
  family = student,
  chains = 4, iter = 2000, warmup = 1000,
  cores = 4, seed = 1234,
  save_pars = save_pars(all = TRUE),
  backend = "cmdstanr",
  file = paste0(root.dir, "/Results/Output/Model_exc/distance_cat_m0")
)
#plot(m_null)
summary(m_null)

# Line model (line_f)
m_line <- brm(
  bf(distance_cat ~ 1 + line_f),
  data = d,
  family = student,
  chains = 4, iter = 2000, warmup = 1000,
  cores = 4, seed = 1234,
  save_pars = save_pars(all = TRUE),
  backend = "cmdstanr",
  file = paste0(root.dir, "/Results/Output/Model_exc/distance_cat_m1")
)
#plot(m_line)
summary(m_line)

# Sex model
m_sex <- brm(
  bf(distance_cat ~ 1 + sex_f),  
  data = d,
  family = student,
  chains = 4, iter = 2000, warmup = 1000,
  cores = 4, seed = 1234,
  save_pars = save_pars(all = TRUE),
  backend = "cmdstanr",
  file = paste0(root.dir, "/Results/Output/Model_exc/distance_cat_m2")
)
#plot(m_sex)
summary(m_sex)

# Intecaction model
m_int <- brm(
  bf(distance_cat ~ 1 + line_f * sex_f),  
  data = d,
  family = student,
  chains = 4, iter = 2000, warmup = 1000,
  cores = 4, seed = 1234,
  save_pars = save_pars(all = TRUE),
  backend = "cmdstanr",
  file = paste0(root.dir, "/Results/Output/Model_exc/distance_cat_m3")
)
#plot(m_int)
summary(m_int)

# Line + sex model
m_line_sex <- brm(
  bf(distance_cat ~ 1 + line_f + sex_f),  
  data = d,
  family = student,
  chains = 4, iter = 2000, warmup = 1000,
  cores = 4, seed = 1234,
  save_pars = save_pars(all = TRUE),
  backend = "cmdstanr",
  file = paste0(root.dir, "/Results/Output/Model_exc/distance_cat_m4")
)
#plot(m_line_sex)
summary(m_line_sex)

## Load all models
m_null <- readRDS(paste0(root.dir, "/Results/Output/Model_exc/distance_cat_m0.rds"))
m_line <- readRDS(paste0(root.dir, "/Results/Output/Model_exc/distance_cat_m1.rds"))
m_sex <- readRDS(paste0(root.dir, "/Results/Output/Model_exc/distance_cat_m2.rds"))
m_int <- readRDS(paste0(root.dir, "/Results/Output/Model_exc/distance_cat_m3.rds"))
m_line_sex <- readRDS(paste0(root.dir, "/Results/Output/Model_exc/distance_cat_m4.rds"))

## Compare models and model selection
m_null <- add_criterion(m_null, "loo", moment_match = TRUE) 
m_line <- add_criterion(m_line, "loo", moment_match = TRUE) 
m_sex <- add_criterion(m_sex, "loo", moment_match = TRUE) 
m_int <- add_criterion(m_int, "loo", moment_match = TRUE) 
m_line_sex <- add_criterion(m_line_sex, "loo", moment_match = TRUE) 
loo_compare(m_null, m_line, m_sex, m_int, m_line_sex) %>% print(simplify = F)

# Remove data
rm(m_null, m_line, m_sex, m_int, m_line_sex)

```


```{r EXC-INC output, warning=F}

## Generate model output for selected model: there were no outliers

# Reload model
m_distance <- readRDS(paste0(root.dir, "/Results/Output/Model_exc/distance_cat_m4.rds"))

# Predict values 
newdata <- expand.grid(line_f = unique(d$line_f),
                       sex_f = unique(d$sex_f))

beta_bayes_pred <- m_distance %>% 
  epred_draws(newdata = newdata)   %>%
  mutate(line_sex = paste(line_f, sex_f, sep="_"))

# Factor
beta_bayes_pred$line_f <- factor(beta_bayes_pred$line_f, levels = c("Control", "WT", "TgTH0", "TgTH-MID", "TgTH-HIGH"),
                                 labels = c("Control", "WT", "TgTH0", "TgTH-MID", "TgTH-HIGH"))
beta_bayes_pred$sex_f <- factor(beta_bayes_pred$sex_f, levels = c(1,2), labels = c("Male", "Female"))
beta_bayes_pred$line_sex_f <- factor(beta_bayes_pred$line_sex,
                                   levels = c("Control_1", "Control_2",
                                              "WT_1","WT_2",
                                              "TgTH0_1","TgTH0_2",
                                              "TgTH-MID_1","TgTH-MID_2",
                                              "TgTH-HIGH_1", "TgTH-HIGH_2"),
                                   labels = c("Control Male", "Control Female",
                                              "WT Male",  "WT Female", 
                                              "TgTH0 Male", "TgTH0 Female",
                                              "TgTH-MID Male","TgTH-MID Female",
                                              "TgTH-HIGH Male", "TgTH-HIGH Female"))
# Generate plot
ggplot(beta_bayes_pred, aes(x = .epred, y = fct_rev(line_sex_f), fill = line_f, alpha = sex_f)) +
  theme_bw() +
  stat_halfeye(.width = c(0.95), point_interval = "mean_qi") +
  scale_fill_viridis_d(option = "plasma", end = 0.8) +
  guides(fill = "none") +
  labs(x = "Distance (cm) moved in the cat zone", y = NULL, alpha= "Sex") +
  scale_alpha_discrete(range = c(0.3, 0.9), guide = guide_legend(override.aes = list(fill = "black"))) +
  theme(legend.position = "bottom") 

ggsave(paste0(root.dir, "/Results/Graphs/Model_exc/distance_m4_EXC_INC.png"), width = 5, height = 3)

# Generate table
beta_bayes_pred_table <- m_distance %>% 
  epred_draws(newdata = newdata)  %>% mean_qi() %>% select(sex_f, line_f, .epred, .lower, .upper) %>% 
  rename_with(~c("Sex", "Line", "Mean", "95% CI lower limit", "95% CI upper limit")) %>% mutate(across(3:5, round, 3),
                                                                                                Sex = ifelse(Sex == 1, "Male", "Female"))
flextable(beta_bayes_pred_table) %>% save_as_docx( path = paste0(root.dir, "/Results/Tables/distance_m4_EXC_INC.docx"))

# create contrasts
t <- beta_bayes_pred %>% 
  dplyr::ungroup() %>% 
  dplyr::select(-c(.row, line_f, sex_f, line_sex_f)) %>% 
  pivot_wider(names_from = "line_sex", values_from = ".epred") %>% 
  mutate(`Control_TgTH0_1` = `Control_1` - `TgTH0_1`,
         `Control_TgTH-MID_1` = `Control_1` - `TgTH-MID_1`,
         `Control_TgTH-HIGH_1` = `Control_1` - `TgTH-HIGH_1`,
         `TgTH0_TgTH-MID_1` = `TgTH0_1` - `TgTH-MID_1`,
         `TgTH0_TgTH-HIGH_1` = `TgTH0_1` - `TgTH-HIGH_1`,
         `TgTH-MID_TgTH-HIGH_1` = `TgTH-MID_1` - `TgTH-HIGH_1`,
         `WT_Control_1` = `WT_1` - `Control_1`,
         `WT_TgTH0_1` = `WT_1` - `TgTH0_1`,
         `WT_TgTH-MID_1` = `WT_1` - `TgTH-MID_1`,
         `WT_TgTH-HIGH_1` = `WT_1` - `TgTH-HIGH_1`,
         
         `Control_TgTH0_2` = `Control_2` - `TgTH0_2`,
         `Control_TgTH-MID_2` = `Control_2` - `TgTH-MID_2`,
         `Control_TgTH-HIGH_2` = `Control_2` - `TgTH-HIGH_2`,
         `TgTH0_TgTH-MID_2` = `TgTH0_2` - `TgTH-MID_2`,
         `TgTH0_TgTH-HIGH_2` = `TgTH0_2` - `TgTH-HIGH_2`,
         `TgTH-MID_TgTH-HIGH_2` = `TgTH-MID_2` - `TgTH-HIGH_2`,
         `WT_Control_2` = `WT_2` - `Control_2`,
         `WT_TgTH0_2` = `WT_2` - `TgTH0_2`,
         `WT_TgTH-MID_2` = `WT_2` - `TgTH-MID_2`,
         `WT_TgTH-HIGH_2` = `WT_2` - `TgTH-HIGH_2`) %>%
  pivot_longer(!c(.chain, .iteration, .draw), names_to = "key", values_to = "epred") %>% 
  filter(key %in% c("Control_TgTH0_1", "Control_TgTH-MID_1", "Control_TgTH-HIGH_1",
                    "WT_Control_1",
                    "TgTH0_TgTH-MID_1", "TgTH0_TgTH-HIGH_1", "TgTH-MID_TgTH-HIGH_1",
                    "WT_TgTH0_1", "WT_TgTH-MID_1", "WT_TgTH-HIGH_1",
                    
                    "Control_TgTH0_2", "Control_TgTH-MID_2", "Control_TgTH-HIGH_2",
                    "WT_Control_2",
                    "TgTH0_TgTH-MID_2", "TgTH0_TgTH-HIGH_2", "TgTH-MID_TgTH-HIGH_2",
                    "WT_TgTH0_2", "WT_TgTH-MID_2", "WT_TgTH-HIGH_2")) %>%
  mutate(key = factor(key, levels = c("Control_TgTH0_1", "Control_TgTH-MID_1", "Control_TgTH-HIGH_1",
                                      "WT_Control_1",
                                      "TgTH0_TgTH-MID_1", "TgTH0_TgTH-HIGH_1", "TgTH-MID_TgTH-HIGH_1",
                                      "WT_TgTH0_1", "WT_TgTH-MID_1", "WT_TgTH-HIGH_1",
                                      
                                      "Control_TgTH0_2", "Control_TgTH-MID_2", "Control_TgTH-HIGH_2",
                                      "WT_Control_2",
                                      "TgTH0_TgTH-MID_2", "TgTH0_TgTH-HIGH_2", "TgTH-MID_TgTH-HIGH_2",
                                      "WT_TgTH0_2", "WT_TgTH-MID_2", "WT_TgTH-HIGH_2"), 
                      labels = c("M Control - TgTH0", "M Control - TgTH-MID", "M Control - TgTH-HIGH",
                                 "M WT - Control",
                                 "M TgTH0 - TgTH-MID", "M TgTH0 - TgTH-HIGH", "M TgTH-MID - TgTH-HIGH",
                                 "M WT - TgTH0", "M WT - TgTH-MID", "M WT - TgTH-HIGH",
                                 
                                 "F Control - TgTH0", "F Control - TgTH-MID", "F Control - TgTH-HIGH",
                                 "F WT - Control",
                                 "F TgTH0 - TgTH-MID", "F TgTH0 - TgTH-HIGH", "F TgTH-MID - TgTH-HIGH",
                                 "F WT - TgTH0", "F WT - TgTH-MID", "F WT - TgTH-HIGH")))  %>%
  group_by(key) %>% mean_qi(epred) %>% 
  mutate(sex = ifelse(substr(key,1,1)== "M", "Male", "Female"),
         contrast = gsub('F ', '', key),
         contrast = gsub('M ', '', contrast)) %>%
  select(key, sex, contrast, epred, .lower, .upper) %>% 
  rename_with(~c("Sex-lines", "Sex", "Lines", "Mean", "95% CI lower limit", "95% CI upper limit"))  %>% mutate(across(4:6, round, 0))

flextable(t) %>% save_as_docx( path = paste0(root.dir, "/Results/Tables/distance_m4_EXC_INC_contrasts.docx"))

# Removed data
rm(beta_bayes_pred, beta_bayes_pred_table, m_distance, newdata, t)

```
